# Generated by Django 2.1 on 2019-03-22 17:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    replaces = [('validator', '0001_initial'), ('validator', '0002_auto_20180926_1434'), ('validator', '0003_auto_20181005_1632'), ('validator', '0004_validationrun_name_tag'), ('validator', '0005_auto_20181006_1722'), ('validator', '0006_auto_20181006_1753'), ('validator', '0007_datafilter_name'), ('validator', '0008_init_filters'), ('validator', '0009_auto_20181013_1221'), ('validator', '0010_auto_20181030_1158'), ('validator', '0011_fill_progress_20181113_1618'), ('validator', '0012_init_filters2'), ('validator', '0013_auto_20181121_1919'), ('validator', '0014_auto_20181121_2009'), ('validator', '0015_auto_20181127_1707'), ('validator', '0016_auto_20181130_1538'), ('validator', '0017_convert_datasets_20181130_1655'), ('validator', '0018_convert_validation_datasets_20181130_1746'), ('validator', '0019_settings'), ('validator', '0020_auto_20190311_0741')]

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('organisation', models.CharField(blank=True, max_length=50)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='DataFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=80)),
                ('help_text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30)),
                ('pretty_name', models.CharField(max_length=30)),
                ('help_text', models.CharField(max_length=150)),
                ('source_reference', models.TextField()),
                ('citation', models.TextField()),
                ('is_reference', models.BooleanField(default=False)),
                ('filters', models.ManyToManyField(related_name='filters', to='validator.DataFilter')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30)),
                ('pretty_name', models.CharField(max_length=30)),
                ('help_text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DataVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30)),
                ('pretty_name', models.CharField(max_length=30)),
                ('help_text', models.CharField(max_length=150)),
                ('min_value', models.FloatField(null=True)),
                ('max_value', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_tag', models.CharField(blank=True, max_length=80)),
                ('start_time', models.DateTimeField(verbose_name='started')),
                ('end_time', models.DateTimeField(null=True, verbose_name='finished')),
                ('total_points', models.IntegerField(default=0)),
                ('error_points', models.IntegerField(default=0)),
                ('ok_points', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
                ('scaling_ref', models.CharField(choices=[('data', 'data to reference'), ('ref', 'reference to data')], default='data', max_length=4)),
                ('scaling_method', models.CharField(choices=[('min_max', 'Min/Max'), ('linreg', 'Linear regression'), ('mean_std', 'Mean/standard deviation')], default='mean_std', max_length=20)),
                ('interval_from', models.DateTimeField(null=True)),
                ('interval_to', models.DateTimeField(null=True)),
                ('output_file', models.FileField(null=True, upload_to='')),
                ('data_dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_dataset', to='validator.Dataset')),
                ('data_filters', models.ManyToManyField(related_name='data_filters', to='validator.DataFilter')),
                ('data_variable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_variable', to='validator.DataVariable')),
                ('data_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_version', to='validator.DatasetVersion')),
                ('ref_dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ref_dataset', to='validator.Dataset')),
                ('ref_filters', models.ManyToManyField(related_name='ref_filters', to='validator.DataFilter')),
                ('ref_variable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ref_variable', to='validator.DataVariable')),
                ('ref_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ref_version', to='validator.DatasetVersion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='variables',
            field=models.ManyToManyField(related_name='variables', to='validator.DataVariable'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='versions',
            field=models.ManyToManyField(related_name='versions', to='validator.DatasetVersion'),
        ),
        migrations.AddField(
            model_name='celerytask',
            name='validation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validation', to='validator.ValidationRun'),
        ),
    ]
