# Generated by Django 2.1.7 on 2019-03-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_squashed_prep_for_new_schema_20190326_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationrun',
            name='data_dataset',
        ),
        migrations.RemoveField(
            model_name='validationrun',
            name='data_filters',
        ),
        migrations.RemoveField(
            model_name='validationrun',
            name='data_variable',
        ),
        migrations.RemoveField(
            model_name='validationrun',
            name='data_version',
        ),
        migrations.RemoveField(
            model_name='validationrun',
            name='ref_dataset',
        ),
        migrations.RemoveField(
            model_name='validationrun',
            name='ref_filters',
        ),
        migrations.RemoveField(
            model_name='validationrun',
            name='ref_variable',
        ),
        migrations.RemoveField(
            model_name='validationrun',
            name='ref_version',
        ),
        migrations.RemoveField(
            model_name='validationrun',
            name='scaling_ref',
        ),
    ]
