# Generated by Django 2.1 on 2018-09-26 14:34

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
