# Generated by Django 2.1 on 2019-04-02 14:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0002_change_celery_task_id_20190327_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celerytask',
            name='celery_task',
        ),
        migrations.RemoveField(
            model_name='celerytask',
            name='id',
        ),
        migrations.AddField(
            model_name='celerytask',
            name='celery_task_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='validation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='celery_tasks', to='validator.ValidationRun'),
        ),
    ]
