# Generated by Django 2.1 on 2018-10-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0002_auto_20180926_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrun',
            name='scaling_method',
            field=models.CharField(choices=[('min_max', 'Min/Max'), ('linreg', 'Linear regression'), ('mean_std', 'Mean/standard deviation')], default='mean_std', max_length=20),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='scaling_ref',
            field=models.CharField(choices=[('data', 'data to reference'), ('ref', 'reference to data')], default='data', max_length=4),
        ),
    ]
