# Generated by Django 2.2 on 2019-04-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0005_mulitple_datasets_part_2_20190402_1650'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='datasetconfiguration',
            order_with_respect_to='validation',
        ),
    ]
