# Generated by Django 2.2 on 2019-05-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0006_auto_20190425_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrun',
            name='output_file',
            field=models.FileField(max_length=250, null=True, upload_to=''),
        ),
    ]
