# Generated by Django 2.2 on 2019-07-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0007_auto_20190517_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='anomalies',
            field=models.BooleanField(default=False),
        ),
    ]
