# Generated by Django 2.1 on 2018-10-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0008_init_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrun',
            name='data_dataset',
            field=models.CharField(choices=[('C3S', 'C3S'), ('ISMN', 'ISMN'), ('GLDAS', 'GLDAS'), ('SMAP', 'SMAP level 3')], default='C3S', max_length=10),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='data_variable',
            field=models.CharField(choices=[('sm', 'sm'), ('soil moisture', 'soil moisture'), ('soil_moisture', 'soil_moisture'), ('SoilMoi0_10cm_inst', 'SoilMoi0_10cm_inst'), ('SoilMoi10_40cm_inst', 'SoilMoi10_40cm_inst'), ('SoilMoi40_100cm_inst', 'SoilMoi40_100cm_inst'), ('SoilMoi100_200cm_inst', 'SoilMoi100_200cm_inst')], default='sm', max_length=20),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='data_version',
            field=models.CharField(choices=[('v201706', 'v201706'), ('v20180712_TEST', '20180712 testset'), ('v20180712_MINI', '20180712 mini testset'), ('V20180830_GLOBAL', '20180830 global'), ('v5_PM', 'v5 PM/ascending'), ('GLDAS_NOAH025_3H.2.1', 'NOAH025 3H.2.1')], default='v201706', max_length=20),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='ref_dataset',
            field=models.CharField(choices=[('C3S', 'C3S'), ('ISMN', 'ISMN'), ('GLDAS', 'GLDAS'), ('SMAP', 'SMAP level 3')], default='ISMN', max_length=10),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='ref_variable',
            field=models.CharField(choices=[('sm', 'sm'), ('soil moisture', 'soil moisture'), ('soil_moisture', 'soil_moisture'), ('SoilMoi0_10cm_inst', 'SoilMoi0_10cm_inst'), ('SoilMoi10_40cm_inst', 'SoilMoi10_40cm_inst'), ('SoilMoi40_100cm_inst', 'SoilMoi40_100cm_inst'), ('SoilMoi100_200cm_inst', 'SoilMoi100_200cm_inst')], default='soil moisture', max_length=20),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='ref_version',
            field=models.CharField(choices=[('v201706', 'v201706'), ('v20180712_TEST', '20180712 testset'), ('v20180712_MINI', '20180712 mini testset'), ('V20180830_GLOBAL', '20180830 global'), ('v5_PM', 'v5 PM/ascending'), ('GLDAS_NOAH025_3H.2.1', 'NOAH025 3H.2.1')], default='v20180712_MINI', max_length=20),
        ),
    ]
