# Generated by Django 2.1.7 on 2019-08-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0008_validationrun_anomalies'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='max_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='max_lon',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='min_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='min_lon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='anomalies',
            field=models.CharField(choices=[('none', "don't calculate"), ('moving_avg_35_d', '35 day moving average'), ('climatology', 'climatology')], default='none', max_length=20),
        ),
    ]
