# Generated by Django 2.2.6 on 2019-11-13 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0009_auto_20190814_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrun',
            name='anomalies',
            field=models.CharField(choices=[('none', 'Do not calculate'), ('moving_avg_35_d', '35 day moving average'), ('climatology', 'Climatology')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='max_lat',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='min_lat',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
    ]
