# Generated by Django 2.2.8 on 2019-12-06 20:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0010_auto_20191113_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafilter',
            name='default_parameter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafilter',
            name='dialog_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='datafilter',
            name='parameterised',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='anomalies_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='anomalies_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='max_lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='max_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='min_lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='min_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ParametrisedFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField()),
                ('dataset_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validator.DatasetConfiguration')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='validator.DataFilter')),
            ],
        ),
        migrations.AddField(
            model_name='datasetconfiguration',
            name='parametrised_filters',
            field=models.ManyToManyField(through='validator.ParametrisedFilter', to='validator.DataFilter'),
        ),
    ]
