# Generated by Django 2.2.8 on 2020-04-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0011_parametrised_filters_20191206_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='detailed_description',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='time_range_covered',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
