# Generated by Django 2.2.8 on 2020-05-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0011_parametrised_filters_20191206_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='last_extended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
