# Generated by Django 2.2.8 on 2020-05-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0012_auto_20200430_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='expiry_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='last_extended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
