# Generated by Django 2.1 on 2018-11-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0013_auto_20181121_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrun',
            name='data_dataset',
            field=models.CharField(choices=[('C3S', 'C3S'), ('SMAP', 'SMAP level 3'), ('ASCAT', 'H-SAF ASCAT SSM CDR'), ('ISMN', 'ISMN'), ('GLDAS', 'GLDAS')], default='C3S', max_length=10),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='ref_dataset',
            field=models.CharField(choices=[('C3S', 'C3S'), ('SMAP', 'SMAP level 3'), ('ASCAT', 'H-SAF ASCAT SSM CDR'), ('ISMN', 'ISMN'), ('GLDAS', 'GLDAS')], default='ISMN', max_length=10),
        ),
    ]
