# Generated by Django 2.1 on 2018-11-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0014_auto_20181121_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrun',
            name='data_version',
            field=models.CharField(choices=[('C3S', (('v201706', 'v201706'),)), ('ISMN', (('v20180712_TEST', '20180712 testset'), ('v20180712_MINI', '20180712 mini testset'), ('V20180830_GLOBAL', '20180830 global'))), ('SMAP', (('v5_PM', 'v5 PM/ascending'),)), ('GLDAS', (('GLDAS_NOAH025_3H.2.1', 'NOAH025 3H.2.1'), ('GLDAS_TEST', 'TEST EIRE'))), ('ASCAT', (('H113', 'H113'),))], default='v201706', max_length=20),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='ref_version',
            field=models.CharField(choices=[('C3S', (('v201706', 'v201706'),)), ('ISMN', (('v20180712_TEST', '20180712 testset'), ('v20180712_MINI', '20180712 mini testset'), ('V20180830_GLOBAL', '20180830 global'))), ('SMAP', (('v5_PM', 'v5 PM/ascending'),)), ('GLDAS', (('GLDAS_NOAH025_3H.2.1', 'NOAH025 3H.2.1'), ('GLDAS_TEST', 'TEST EIRE'))), ('ASCAT', (('H113', 'H113'),))], default='v20180712_MINI', max_length=20),
        ),
    ]
