# Generated by Django 2.2.8 on 2020-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0015_user_orcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='publishing_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
