# Generated by Django 2.1 on 2018-11-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0015_auto_20181127_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30)),
                ('pretty_name', models.CharField(max_length=30)),
                ('help_text', models.CharField(max_length=150)),
                ('source_reference', models.TextField()),
                ('citation', models.TextField()),
                ('is_reference', models.BooleanField(default=False)),
                ('filters', models.ManyToManyField(related_name='filters', to='validator.DataFilter')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30)),
                ('pretty_name', models.CharField(max_length=30)),
                ('help_text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DataVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30)),
                ('pretty_name', models.CharField(max_length=30)),
                ('help_text', models.CharField(max_length=150)),
                ('min_value', models.FloatField(null=True)),
                ('max_value', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='data_version',
            field=models.CharField(choices=[('C3S', (('v201706', 'v201706'),)), ('ISMN', (('v20180712_TEST', '20180712 testset'), ('v20180712_MINI', '20180712 mini testset'), ('V20180830_GLOBAL', '20180830 global'))), ('SMAP', (('v5_PM', 'v5 PM/ascending'),)), ('GLDAS', (('GLDAS_NOAH025_3H.2.1', 'NOAH025 3H.2.1'), ('GLDAS_TEST', 'TEST'))), ('ASCAT', (('H113', 'H113'),))], default='v201706', max_length=20),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='ref_version',
            field=models.CharField(choices=[('C3S', (('v201706', 'v201706'),)), ('ISMN', (('v20180712_TEST', '20180712 testset'), ('v20180712_MINI', '20180712 mini testset'), ('V20180830_GLOBAL', '20180830 global'))), ('SMAP', (('v5_PM', 'v5 PM/ascending'),)), ('GLDAS', (('GLDAS_NOAH025_3H.2.1', 'NOAH025 3H.2.1'), ('GLDAS_TEST', 'TEST'))), ('ASCAT', (('H113', 'H113'),))], default='v20180712_MINI', max_length=20),
        ),
        migrations.AddField(
            model_name='dataset',
            name='variables',
            field=models.ManyToManyField(related_name='variables', to='validator.DataVariable'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='versions',
            field=models.ManyToManyField(related_name='versions', to='validator.DatasetVersion'),
        ),
    ]
