# Generated by Django 2.2.8 on 2020-05-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0016_validationrun_publishing_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetconfiguration',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='dataset_configurations', to='validator.DataFilter'),
        ),
        migrations.AlterField(
            model_name='datasetconfiguration',
            name='parametrised_filters',
            field=models.ManyToManyField(blank=True, through='validator.ParametrisedFilter', to='validator.DataFilter'),
        ),
    ]
