# Generated by Django 2.2.8 on 2020-06-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0017_auto_20200529_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrun',
            name='output_file',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to=''),
        ),
    ]
