# Generated by Django 3.0.8 on 2020-07-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0018_auto_20200610_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='news',
            field=models.TextField(blank=True),
        ),
    ]
