# Generated by Django 3.0.8 on 2020-09-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0019_settings_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='time_range_covered',
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='time_range_end',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='time_range_start',
            field=models.TextField(blank=True, null=True),
        ),
    ]
