# Generated by Django 3.0.8 on 2020-09-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0020_ismnnetworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ismnnetworks',
            name='versions',
            field=models.ManyToManyField(related_name='network_version', to='validator.DatasetVersion'),
        ),
    ]
