# Generated by Django 3.1.1 on 2020-09-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0021_ismnnetworks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='is_reference',
            new_name='is_only_reference',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
