# Generated by Django 3.1.1 on 2020-11-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0021_auto_20200923_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrun',
            name='scaling_method',
            field=models.CharField(choices=[('none', 'No scaling'), ('min_max', 'Min/Max'), ('linreg', 'Linear regression'), ('mean_std', 'Mean/standard deviation')], default='mean_std', max_length=20),
        ),
    ]
