# Generated by Django 3.1.1 on 2020-10-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0021_auto_20200923_1634'),
        ('validator', '0021_ismnnetworks'),
    ]

    operations = [
    ]
