# Generated by Django 3.1.1 on 2020-10-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0022_auto_20200923_1532'),
        ('validator', '0022_merge_20201001_0821'),
    ]

    operations = [
    ]