# Generated by Django 3.1.1 on 2020-10-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0022_merge_20201001_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='ismnnetworks',
            name='station_info',
            field=models.CharField(default='{}', max_length=200000),
        ),
    ]
