# Generated by Django 3.1.1 on 2020-10-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0021_auto_20200923_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_statistics', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
