# Generated by Django 3.1.3 on 2021-01-08 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0025_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRun_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('original_start', models.DateTimeField(verbose_name='started')),
                ('original_end', models.DateTimeField(verbose_name='finished')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('validationrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validator.validationrun')),
            ],
        ),
        migrations.AddField(
            model_name='validationrun',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='copied_runs', through='validator.ValidationRun_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
