# Generated by Django 3.1.3 on 2020-12-18 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0025_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='copied_runs', to=settings.AUTH_USER_MODEL),
        ),
    ]
