# Generated by Django 3.1.3 on 2021-01-15 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0026_auto_20210108_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copiedvalidations',
            name='user',
        ),
        migrations.AddField(
            model_name='copiedvalidations',
            name='used_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
