# Generated by Django 3.1.6 on 2021-07-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0028_auto_20210314_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetversion',
            name='geographical_range',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
