# Generated by Django 3.1.3 on 2021-04-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0029_uptimeagent_uptimeping_uptimereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='uptimereport',
            name='agent_key',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
