# Generated by Django 3.1.3 on 2021-05-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0030_uptimereport_agent_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='uptimereport',
            name='downtime_minutes',
            field=models.IntegerField(default=-1),
        ),
    ]
