# Generated by Django 3.1.3 on 2021-07-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0031_auto_20210505_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafilter',
            name='to_include',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='uptimeping',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
