# Generated by Django 3.1.3 on 2021-07-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0032_auto_20210723_1306'),
        ('validator', '0032_mutually_inclusive_filters'),
    ]

    operations = [
    ]
