# Generated by Django 3.1.3 on 2021-07-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0032_mutual_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafilter',
            name='to_include',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
