# Generated by Django 3.1.3 on 2021-07-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0033_auto_20210622_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafilter',
            name='to_include',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
