# Generated by Django 3.1.3 on 2021-05-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0033_auto_20210531_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrun',
            name='upscaling_method',
            field=models.CharField(choices=[('none', 'Do not upscale point measurements'), ('average', 'Average point measurements')], default='none', max_length=20, null=True),
        ),
    ]
