# Generated by Django 3.1.3 on 2021-09-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0033_mutual_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='copiedvalidations',
            name='original_run_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
