# Generated by Django 3.1.3 on 2021-07-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0033_auto_20210622_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafilter',
            name='disable_filter',
            field=models.IntegerField(null=True),
        ),
    ]
