# Generated by Django 3.1.3 on 2021-09-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0034_copiedvalidations_original_run_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='temporal_stability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='upscaling_method',
            field=models.CharField(blank=True, choices=[('none', 'Do not upscale point measurements'), ('average', 'Average point measurements')], default='none', max_length=50),
        ),
    ]
