# Generated by Django 3.1.3 on 2021-08-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0035_dataset_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetversion',
            name='geographical_range',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
