# Generated by Django 3.1.3 on 2021-08-13 09:54

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0035_dataset_resolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('send_this_email', models.BooleanField(default=False, verbose_name='Send this email')),
                ('sent', models.BooleanField(default=False)),
                ('send_to', models.ManyToManyField(related_name='addressees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
