# Generated by Django 3.1.3 on 2021-10-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0036_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='bootstrap_tcol_cis',
            field=models.BooleanField(default=False),
        ),
    ]
