# Generated by Django 3.2.7 on 2021-11-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0038_auto_20211001_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='bootstrap_tcol_cis',
            field=models.BooleanField(default=False),
        ),
    ]
