# Generated by Django 3.2.9 on 2021-11-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0038_validationrun_bootstrap_tcol_cis'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetversion',
            name='geographical_range',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
