# Generated by Django 3.2.9 on 2021-11-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0036_datasetversion_geographical_range'),
        ('validator', '0038_validationrun_bootstrap_tcol_cis'),
    ]

    operations = [
    ]
