# Generated by Django 3.2.9 on 2021-12-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0039_datasetversion_geographical_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='copiedvalidations',
            name='original_run_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafilter',
            name='to_include',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
