# Generated by Django 3.2.11 on 2022-03-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0040_auto_20211213_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafilter',
            name='default_set_active',
            field=models.BooleanField(default=False),
        ),
    ]
