# Generated by Django 3.2.11 on 2022-03-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0041_datafilter_default_set_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafilter',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datafilter',
            name='help_text',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='datafilter',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
