# Generated by Django 3.2.11 on 2022-05-12 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0042_readonly_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='temporal_matching',
            field=models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
