# Generated by Django 3.2.12 on 2022-06-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0043_validationrun_temporal_matching'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='sum_link',
            field=models.CharField(blank=True, max_length=250, verbose_name='User Manual Link'),
        ),
    ]
