# Generated by Django 3.2.12 on 2022-06-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0044_settings_sum_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='feed_link',
            field=models.CharField(blank=True, max_length=250, verbose_name='Feedback Link'),
        ),
    ]
