# Generated by Django 3.2.12 on 2022-08-25 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import validator.models.user_dataset_file


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0045_settings_feed_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserDatasetFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=validator.models.user_dataset_file.upload_directory)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset', to='validator.dataset')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('variable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variable', to='validator.datavariable')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version', to='validator.datasetversion')),
            ],
        ),
    ]
