# Generated by Django 3.2.12 on 2022-10-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0049_auto_20220928_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datavariable',
            name='pretty_name',
            field=models.CharField(max_length=100),
        ),
    ]
