# Generated by Django 3.2.12 on 2022-09-15 08:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0049_auto_20220912_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatasetfile',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 8, 16, 5, 585993, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
