# Generated by Django 3.2.12 on 2022-11-15 12:03

import django.core.files.storage
from django.db import migrations, models
import validator.models.user_dataset_file


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0050_alter_datavariable_pretty_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validationrun',
            old_name='reference_configuration',
            new_name='spatial_reference_configuration',
        ),
        migrations.AlterField(
            model_name='userdatasetfile',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='./testdata/user_data/'), upload_to=validator.models.user_dataset_file.upload_directory),
        ),
    ]
