# Generated by Django 3.2.12 on 2022-11-15 14:18

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F


def update_scaling_and_temporal_reference_fields(apps, schema_editor):
    ValidationRun = apps.get_model('validator', 'validationrun')
    db_alias = schema_editor.connection.alias
    ValidationRun.objects.using(db_alias).all().update(
        temporal_reference_configuration=F('spatial_reference_configuration'),
        scaling_reference_configuration=F('spatial_reference_configuration')
    )


class Migration(migrations.Migration):
    dependencies = [
        ('validator', '0051_auto_20221115_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='scaling_reference_configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='scal_ref_validation_run', to='validator.datasetconfiguration'),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='temporal_reference_configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='temp_ref_validation_run', to='validator.datasetconfiguration'),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='spatial_reference_configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='spat_ref_validation_run', to='validator.datasetconfiguration'),
        ),
        migrations.RunPython(update_scaling_and_temporal_reference_fields),
    ]
