# Generated by Django 3.2.12 on 2022-11-22 11:50

from django.db import migrations, models
from django.db.models import Q


def update_scaling_and_temporal_reference_fields(apps, schema_editor):
    DatasetConfiguration = apps.get_model('validator', 'datasetconfiguration')
    ValidationRun = apps.get_model('validator', 'validationrun')
    db_alias = schema_editor.connection.alias
    config_ids = list(ValidationRun.objects.using(db_alias).all().values_list('spatial_reference_configuration',
                                                                              flat=True))
    DatasetConfiguration.objects.using(db_alias).all().update(
        is_spatial_reference=Q(id__in=config_ids),
        is_temporal_reference=Q(id__in=config_ids),
    )


class Migration(migrations.Migration):
    dependencies = [
        ('validator', '0053_rename_is_only_reference_dataset_is_spatial_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetconfiguration',
            name='is_spatial_reference',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='datasetconfiguration',
            name='is_temporal_reference',
            field=models.BooleanField(null=True),
        ),
        migrations.RunPython(update_scaling_and_temporal_reference_fields),
    ]
