# Generated by Django 3.2.12 on 2022-12-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0054_auto_20221122_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrun',
            name='scaling_method',
            field=models.CharField(choices=[('none', 'No scaling'), ('min_max', 'Min/Max'), ('linreg', 'Linear regression'), ('mean_std', 'Mean/standard deviation'), ('cdf_beta_match', 'CDF matching with beta distribution fitting')], default='none', max_length=20),
        ),
    ]
