# Generated by Django 3.2.12 on 2023-01-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0055_alter_validationrun_scaling_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatasetfile',
            name='lat_name',
        ),
        migrations.RemoveField(
            model_name='userdatasetfile',
            name='lon_name',
        ),
        migrations.RemoveField(
            model_name='userdatasetfile',
            name='time_name',
        ),
    ]
