# Generated by Django 3.2.12 on 2023-01-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0055_alter_validationrun_scaling_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetversion',
            name='pretty_name',
            field=models.CharField(max_length=40),
        ),
    ]
