# Generated by Django 3.2.12 on 2023-01-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0056_alter_datasetversion_pretty_name'),
        ('validator', '0056_auto_20230118_1116'),
    ]

    operations = [
    ]
