# Generated by Django 3.2.12 on 2023-01-26 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0057_merge_20230120_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatasetfile',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_dataset', to='validator.dataset'),
        ),
        migrations.AlterField(
            model_name='userdatasetfile',
            name='variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_variable', to='validator.datavariable'),
        ),
        migrations.AlterField(
            model_name='userdatasetfile',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_version', to='validator.datasetversion'),
        ),
    ]
