# Generated by Django 3.2.12 on 2023-02-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0058_auto_20230126_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavariable',
            name='unit',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
