# Generated by Django 3.2.12 on 2023-02-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0059_datavariable_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datavariable',
            name='unit',
            field=models.CharField(default='n.a.', max_length=20),
        ),
    ]
