# Generated by Django 3.2.12 on 2023-03-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0060_alter_datavariable_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='plots_save_metadata',
            field=models.CharField(choices=[('always', 'force creating metadata box plots (e.g. for testing)'), ('never', 'do not create metadata box plots at all'), ('threshold', 'create metadata box plots only when the minimum number of required points is available (set in globals of qa4sm-reader')], default='threshold', max_length=10),
        ),
    ]
