# Generated by Django 3.2.12 on 2023-02-23 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_unlimited_data_space_for_staff_user(apps, schema_editor):
    User = apps.get_model('validator', 'user')
    db_alias = schema_editor.connection.alias
    User.objects.using(db_alias).filter(is_staff=True).update(data_space='unlimited')


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0061_validationrun_plots_save_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_space',
            field=models.CharField(blank=True, choices=[('no_data', 1), ('basic', 5000000000), ('extended', 10000000000), ('unlimited', None)], default='basic', max_length=25),
        ),
        migrations.AlterField(
            model_name='userdatasetfile',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_unlimited_data_space_for_staff_user),
    ]
