# Generated by Django 3.2.12 on 2023-03-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0062_auto_20230223_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatasetfile',
            name='metadata_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
