# Generated by Django 3.2.16 on 2023-06-23 09:20

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


def create_dataset_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    DataManagementGroup = apps.get_model('validator', 'DataManagementGroup')

    content_type = ContentType.objects.get_for_model(DataManagementGroup)

    publish_datamanagementgroup = Permission.objects.create(
        codename='publish_datamanagementgroup',
        name='Can publish validations with dataset',
        content_type=content_type,
    )
    publish_datamanagementgroup.save()

    download_datamanagementgroup = Permission.objects.create(
        codename='download_datamanagementgroup',
        name='Can download dataset file',
        content_type=content_type,
    )
    download_datamanagementgroup.save()


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('validator', '0063_userdatasetfile_metadata_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataManagementGroup',
            fields=[
                ('group_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='auth.group')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        # migrations.RunPython(create_dataset_permissions),
    ]
