# Generated by Django 3.2.16 on 2023-07-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0067_alter_user_space_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='filters',
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='filters',
            field=models.ManyToManyField(related_name='filters', to='validator.DataFilter'),
        ),
    ]
