# Generated by Django 3.2.16 on 2023-07-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0068_auto_20230719_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetversion',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='filters', to='validator.DataFilter'),
        ),
    ]
