# Generated by Django 3.2.16 on 2023-09-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0069_alter_datasetversion_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatasetfile',
            name='user_groups',
        ),
        migrations.AddField(
            model_name='dataset',
            name='user_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='custom_datasets', to='validator.DataManagementGroup'),
        ),
    ]
