# Generated by Django 3.2.16 on 2023-10-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0070_auto_20230908_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafilter',
            name='disable_filter',
        ),
        migrations.AddField(
            model_name='datafilter',
            name='to_exclude',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
