# Generated by Django 3.2.16 on 2023-11-22 13:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0071_auto_20231027_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='./docs/'), upload_to='./user_manual')),
                ('upload_date', models.DateTimeField()),
            ],
        ),
    ]
