# Generated by Django 3.2.16 on 2023-11-21 13:11

import django.core.files.storage
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0071_auto_20231027_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='./docs/'), upload_to='./files_to_serve')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_date', models.DateTimeField()),
            ],
        ),
    ]
