# Generated by Django 3.2.16 on 2024-03-19 09:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0072_usermanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanual',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/'), upload_to='./user_manual'),
        ),
    ]
