# Generated by Django 3.2.16 on 2024-10-02 08:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0073_alter_usermanual_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='potential_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='potential_maintenance_description',
            field=models.TextField(blank=True),
        ),
    ]
