# Generated by Django 3.2.16 on 2024-07-16 13:46

import django.core.files.storage
from django.db import migrations, models
import validator.models.user_dataset_file


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0075_alter_usermanual_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='intra_annual_metrics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='intra_annual_overlap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='intra_annual_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
