# Generated by Django 3.2.16 on 2025-02-14 14:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0076_auto_20241011_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='status',
            field=models.CharField(choices=[('DONE', 'Done'), ('SCHEDULED', 'Scheduled'), ('ERROR', 'Error'), ('RUNNING', 'Running'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=10),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='DOCS_DIR'), upload_to='./user_manual'),
        ),
    ]
