# Generated by Django 3.2.16 on 2025-02-14 13:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0076_auto_20241011_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanual',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='DOCS_DIR'), upload_to='./user_manual'),
        ),
    ]
