# Generated by Django 3.2.16 on 2024-09-19 11:42

import django.core.files.storage
from django.db import migrations, models
import validator.models.user_dataset_file


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0077_alter_validationrun_intra_annual_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='stability_metrics',
            field=models.BooleanField(default=False),
        ),
    ]
