# Generated by Django 5.1.6 on 2025-03-25 14:06

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0078_remove_validationrun_is_removed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedValidationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='started')),
                ('end_time', models.DateTimeField(null=True, verbose_name='finished')),
                ('total_points', models.IntegerField(default=0)),
                ('error_points', models.IntegerField(default=0)),
                ('ok_points', models.IntegerField(default=0)),
                ('datasets', models.JSONField(default=list)),
                ('spatial_reference', models.CharField(default=None, null=True)),
                ('temporal_reference', models.CharField(default=None, null=True)),
                ('scaling_reference', models.CharField(default=None, null=True)),
                ('scaling_method', models.CharField(default=None, max_length=20)),
                ('interval_from', models.DateTimeField(null=True)),
                ('interval_to', models.DateTimeField(null=True)),
                ('anomalies', models.CharField(default=None, max_length=20)),
                ('min_lat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('min_lon', models.FloatField(blank=True, null=True)),
                ('max_lat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('max_lon', models.FloatField(blank=True, null=True)),
                ('anomalies_from', models.DateTimeField(blank=True, null=True)),
                ('anomalies_to', models.DateTimeField(blank=True, null=True)),
                ('upscaling_method', models.CharField(blank=True, max_length=50)),
                ('temporal_stability', models.BooleanField(default=False)),
                ('tcol', models.BooleanField(default=False)),
                ('bootstrap_tcol_cis', models.BooleanField(default=False)),
                ('temporal_matching', models.IntegerField(blank=True, default=None)),
                ('plots_save_metadata', models.CharField(choices=[('always', 'force creating metadata box plots (e.g. for testing)'), ('never', 'do not create metadata box plots at all'), ('threshold', 'create metadata box plots only when the minimum number of required points is available (set in globals of qa4sm-reader')], default='threshold', max_length=10)),
                ('intra_annual_metrics', models.BooleanField(default=False)),
                ('intra_annual_type', models.CharField(blank=True, max_length=100, null=True)),
                ('intra_annual_overlap', models.IntegerField(blank=True, null=True)),
                ('stability_metrics', models.BooleanField(default=False)),
                ('status', models.CharField(default='DONE', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
