# Generated by Django 5.1.6 on 2025-04-30 09:51

import django.core.files.storage
from django.db import migrations, models

def move_variables_from_dataset_to_version(apps, schema_editor):
    dataset_model = apps.get_model('validator', 'Dataset')

    for dataset in dataset_model.objects.all():
        print(dataset.variables.all())
        for version in dataset.versions.all():  # adjust if you use a related_name
            version.variables.set(dataset.variables.all())
            version.save()



class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0080_datasetversion_variables'),
    ]

    operations = [
        migrations.RunPython(move_variables_from_dataset_to_version),
    ]
