# Generated by Django 5.1.6 on 2025-05-05 13:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0082_remove_dataset_variables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ismnnetworks',
            name='number_of_stations',
        ),
    ]
