# Generated by Django 5.1.6 on 2025-07-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0083_remove_ismnnetworks_number_of_stations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="space_limit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_data", 1),
                    ("basic", 5000000000),
                    ("extended", 10000000000),
                    ("active", 20000000000),
                    ("regular", 50000000000),
                    ("frequent", 75000000000),
                    ("power_user", 100000000000),
                    ("large", 200000000000),
                    ("unlimited", None),
                ],
                default="basic",
                max_length=25,
            ),
        ),
    ]
