# Generated by Django 5.1.6 on 2025-08-04 13:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0084_alter_user_space_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatasetfile',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatasetfile',
            name='log_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatasetfile',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='DOCS_DIR'), upload_to='./user_manual'),
        ),
    ]
