# Generated by Django 5.1.6 on 2025-09-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0087_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManual',
        ),
    ]
