# Generated by Django 5.1.6 on 2025-10-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0087_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationrun",
            name="geotiff_path",
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
