# Generated by Django 5.1.6 on 2026-01-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0088_delete_usermanual"),
    ]

    operations = [
        migrations.AddField(
            model_name="datavariable",
            name="display_name",
            field=models.CharField(max_length=100, default='n.a.', blank=True),
        ),
    ]
