# Generated by Django 5.1.6 on 2026-02-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0089_datavariable_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdatasetfile",
            name="original_file_size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
