# Generated by Django 5.1.15 on 2026-03-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0090_userdatasetfile_original_file_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdatasetfile",
            name="original_file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
