# Generated by Django 5.1.15 on 2026-03-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0091_alter_userdatasetfile_original_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedvalidationrun',
            name='val_type',
            field=models.CharField(blank=True, default='temporal', max_length=10),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='output_file_spatial',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='val_type',
            field=models.CharField(choices=[('temporal', 'Temporal only'), ('spatial', 'Spatial only'), ('both', 'Both')], default='temporal', max_length=10),
        ),
    ]
