# Generated by Django 5.1.15 on 2026-03-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0092_deletedvalidationrun_val_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedvalidationrun',
            name='error_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deletedvalidationrun',
            name='ok_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deletedvalidationrun',
            name='total_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='error_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='ok_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='progress_spatial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='total_times',
            field=models.IntegerField(default=0),
        ),
    ]
