# Generated by Django 5.1.15 on 2026-08-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0094_dataset_plot_resolution_validationrun_zarr_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="datavariable",
            name="depth_from",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datavariable",
            name="depth_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("layer", "Disjoint depth layer"),
                    ("aggregate", "Pre-averaged over a depth span"),
                    ("", "Depth not applicable"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="datavariable",
            name="depth_to",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="datavariable",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("depth_kind", ""),
                    models.Q(
                        ("depth_from__isnull", False), ("depth_to__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="depth_bounds_required_when_kind_declared",
            ),
        ),
    ]
