# Generated by Django 5.1.15 on 2026-08-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0095_datavariable_depth_from_datavariable_depth_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetconfiguration",
            name="merge_weighted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="datasetconfiguration",
            name="merged_variables",
            field=models.ManyToManyField(
                blank=True,
                related_name="merged_in_configs",
                to="validator.datavariable",
            ),
        ),
    ]
